Sort PGDL temperature profiles to be monotonic
USGS-R/mntoha-data-release pull request #31
Opened 2021-02-24 15:46 UTC by hcorson-dosch

* Add in task table targets to `5_predictions.yml` to sort all pgdl final predictions and pgdl test predictions to be monotonic with regards to temperature, prior to evaluation step
* Add target in `remake.yml` to push PGDL predictions to SB

2021-02-24 17:13 UTC, lindsayplatt requested changes
Great first implementation of a task makefile! Added a few things that I think will help polish it up. 

I added a comment about the use of `tempdir()` mostly as a question to think about. I am not sure if it makes a difference, but it is worth thinking about.

2021-02-24 17:13 UTC, lindsayplatt commented on src/file_utils.R
> +#     zip(zippath, files = files_to_zip)
Did you want to delete?

2021-02-24 17:13 UTC, lindsayplatt commented on src/file_utils.R
> +#     file.copy(these_files$source_filepath, file.path(tempdir(), these_files$out_file))
You might want to delete instead of just comment out.

2021-02-25 15:03 UTC, hcorson-dosch commented on 5_predictions.yml
> +          prediction_files = I('pgdl_predictions_df'),
That is how I initially coded it, but I could not get it to work, no matter what I tried.

I tried passing the command in `5_predictions.yml` like this:
```
out/pgdl_predictions_final_sorted.ind:
      command: do_sorting_tasks(
          final_target = target_name,
          site_id_list = pgdl_lake_ids,
          prediction_files = pgdl_predictions_df,
          prediction_type = I('pgdl_final'),
          'src/do_sorting_tasks.R',
          'src/file_utils.R')
```

Then tried 3 ways of building the step task command:

1) passing it with no quotes or notation
```
filepaths_step <- create_task_step(
        step_name = 'filepaths',
        target_name = function(task_name, step_name, ...) {
            sprintf('tmp/%s_%s_%s.csv', task_name, step_name, prediction_type)
        },
        command = function(task_name, target_name, step_name, ...) {
            psprintf("subset_prediction_files(",
                     "outfile = target_name,",
                     "site_id = I('%s')," = task_name,
                     "prediction_files = %s)" = prediction_files
                    )
        }
    )
```

2) Passing it with `  notation
```
filepaths_step <- create_task_step(
        step_name = 'filepaths',
        target_name = function(task_name, step_name, ...) {
            sprintf('tmp/%s_%s_%s.csv', task_name, step_name, prediction_type)
        },
        command = function(task_name, target_name, step_name, ...) {
            psprintf("subset_prediction_files(",
                     "outfile = target_name,",
                     "site_id = I('%s')," = task_name,
                     "prediction_files = `%s`)" = prediction_files
                    )
        }
    )
```
With both of those two I get this in the `pgdl_final_sorting_tasks.yml`
```
tmp/nhdhr_{61868B30-FEF4-40E3-B121-F0430D80D776}_filepaths_pgdl_final.csv:
    command: subset_prediction_files(
      outfile = target_name,
      site_id = I('nhdhr_{61868B30-FEF4-40E3-B121-F0430D80D776}'),
      c(&quot;prediction_files = `nhdhr_{4EA76133-68CD-4DA8-A82B-0B568CD9C9B2}`)&quot;, &quot;prediction_files = `nhdhr_{61868B30-FEF4-40E3-B121-F0430D80D776}`)&quot;, &quot;prediction_files = `nhdhr_{820B0DD5-51F5-4C99-AB26-F63B5612E309}`)&quot;, &quot;prediction_files = `nhdhr_{E7E928FD-5D66-4B1E-8276-87C708CA2842}`)&quot;, &quot;prediction_files = `nhdhr_{F64EAA10-6765-45AE-8EE6-572B30A7B573}`)&quot;, &quot;prediction_files = `nhdhr_{FC091A8F-FC45-46C0-91F9-18379CF0EAAE}`)&quot;, &quot;prediction_files = `nhdhr_0E445706-1F3E-47FA-8A83-D38E2C953307`)&quot;, &quot;prediction_files = `nhdhr_105567402`)&quot;, ........
```

3) Pass it directly (like `target_name` ):
```
filepaths_step <- create_task_step(
        step_name = 'filepaths',
        target_name = function(task_name, step_name, ...) {
            sprintf('tmp/%s_%s_%s.csv', task_name, step_name, prediction_type)
        },
        command = function(task_name, target_name, step_name, ...) {
            psprintf("subset_prediction_files(",
                     "outfile = target_name,",
                     "site_id = I('%s')," = task_name,
                     "prediction_files = prediction_files)"
                    )
        }
    )
```
With that I get:
```
tmp/nhdhr_{4EA76133-68CD-4DA8-A82B-0B568CD9C9B2}_filepaths_pgdl_final.csv:
    command: subset_prediction_files(
      outfile = target_name,
      site_id = I('nhdhr_{4EA76133-68CD-4DA8-A82B-0B568CD9C9B2}'),
      prediction_files = prediction_files)
```

And I can't pass it indirectly (through `...` in `do_sorting_tasks.R` ) as a depends, like so:
```
  out/pgdl_predictions_final_sorted.ind:
      command: do_sorting_tasks(
          final_target = target_name,
          site_id_list = pgdl_lake_ids,
          prediction_type = I('pgdl_final'),
          'src/do_sorting_tasks.R',
          'src/file_utils.R')
      depends: pgdl_predictions_df 
```
Because I can't call it out by name in `do_sorting_tasks.R` because I need to use that function for both the final predictions and the test predictions, so can't call out a specific object in the function. Even thought that works perfectly if you weren't trying to reuse the task table code. What I'm referring to would look like something we did in the pipelines course, like so:
```
filepaths_step <- create_task_step(
        step_name = 'filepaths',
        target_name = function(task_name, step_name, ...) {
            sprintf('tmp/%s_%s_%s.csv', task_name, step_name, prediction_type)
        },
        command = function(task_name, target_name, step_name, ...) {
            psprintf("subset_prediction_files(",
                     "outfile = target_name,",
                     "site_id = I('%s')," = task_name,
                     "prediction_files = pgdl_predictions_df)"
                    )
        }
    )
```
I suppose I could add an if statement that depends on the prediction type passed in, but that still would mean passing the dataframe object as a depends, which is what we were trying to avoid

I'm probably missing something obvious here.... but I did try! Any ideas?

2021-02-25 15:04 UTC, hcorson-dosch commented on 5_predictions.yml
> +          prediction_files = I('pgdl_test_predictions_df'),
I agree this would be cleaner. See above notes ^

2021-02-25 15:04 UTC, hcorson-dosch commented on pgdl_final_sorting_tasks.yml
> +# Do not edit - automatically generated
Got - makes sense. I removed them from the cache

2021-02-25 15:05 UTC, hcorson-dosch commented on pgdl_test_sorting_tasks.yml
> +# Do not edit - automatically generated
👍

2021-02-25 15:10 UTC, hcorson-dosch commented on src/do_sorting_tasks.R
> +    pgdl_unsorted <- readr::read_csv(file.path(tempdir(), site_filepaths$raw_file))
I don't really like the `tempdir()` myself, and originally coded everythig to be in `/tmp`, but then I realized that other functions were relying on those files being in `tempdir()` instead, so I changed it. I could re-work that if we think it would be better in `tmp/`. It is a bit tricky now in that you have to build `out/5_pgdl_test_predictions_zips.yml` right after building `out/pgdl_predictions_test_sorted.ind`, since it is building the former that copies the files to `tempdir()` (sorting the data in the process), and the latter that zips those files. Previously, it all happened in that one zips target, so it wasn't an issue. Thoughts? Maybe I should re-work the code a bit to place everything in `tmp/` instead. That way the sorted data would also be accessible, instead of hidden in `tempdir()`

2021-02-25 15:21 UTC, hcorson-dosch commented on src/file_utils.R
> +#     zip(zippath, files = files_to_zip)
Sorry 😬. Sloppy code. I was battling through issues mixing `tmp/` and `tempdir()` here. The code setting the working directory to `tempdir()` sometime really trips things up.

2021-02-25 15:40 UTC, lindsayplatt commented on src/do_sorting_tasks.R
> +    pgdl_unsorted <- readr::read_csv(file.path(tempdir(), site_filepaths$raw_file))
I think `tmp/` is safer when things are in different targets because you may not want to build back-to-back. That said, we are on a time crunch here. Maybe you can make an issue in this repo about that instead and we can circle back later?

2021-02-25 15:40 UTC, lindsayplatt commented on src/file_utils.R
> +#     zip(zippath, files = files_to_zip)
It's easy to forget to come back to these kind of things :)

2021-02-25 15:47 UTC, lindsayplatt commented on 5_predictions.yml
> +          prediction_files = I('pgdl_predictions_df'),
Glad to see you thought about it and tried so many things! I think that last piece comes closer to what I think would work, but I actually have an idea that might help this be a non-issue. Let's chat!

2021-02-26 18:50 UTC, hcorson-dosch commented on src/do_sorting_tasks.R
> +    pgdl_unsorted <- readr::read_csv(file.path(tempdir(), site_filepaths$raw_file))
Per our discussion, decided to go ahead and fix this now, since having the copy files and zip files steps split between two targets was not ideal if using `tempdir()`

2021-02-26 18:53 UTC, hcorson-dosch commented
@lindsayplatt  made all of the changes we discussed, and made sure that all task table and downstream targets build fine. I did not push to SB, because -- as we noted in our discussion -- none of the model results were affected by these changes, I simply modified the structure of the task table, and changed the code to place prediction files in the `tmp/` folder instead of in `tempdir()`

2021-02-26 19:14 UTC, lindsayplatt reviewed
A few tiny additional comments!

2021-02-26 19:14 UTC, lindsayplatt commented on src/do_sorting_tasks.R
> +    file.copy(infile, file.path(cd, outfile), overwrite=TRUE)
I don't think you need `cd` because by default, it will put the file in your current working directory. You should be able to simplfiy this whole function to just the file.copy fxn and actually, just use that in your step in do_sorting_tasks above. So, STEP 1 could become:

```
psprintf("file.copy(",
     "to= target_name,",
     "from= '%s'," = site_files$source_filepath,
     "overwrite= TRUE)"
)
```

2021-02-26 19:14 UTC, lindsayplatt commented on src/eval_utils.R
> +      unzip(source_zip, overwrite = TRUE)
Would you still want to unzip to `tmp/` ?

2021-02-26 19:14 UTC, lindsayplatt commented on src/file_utils.R
> +        file.copy(these_files$source_filepath, file.path(cd,'tmp', these_files$out_file), overwrite=TRUE)
No need to use `cd`. By default, R will know the current working directory path. Only need to do this kind of approach if `setwd()` is invoked.

2021-02-26 20:04 UTC, hcorson-dosch commented on src/eval_utils.R
> +      unzip(source_zip, overwrite = TRUE)
It actually is still unzipping to tmp -- the folder prefix now comes in with the source_csv column:
![image](https://user-images.githubusercontent.com/54007288/109349431-8f72c880-783b-11eb-9ac9-1a02fbe97d26.png)

2021-02-26 20:11 UTC, hcorson-dosch commented on src/do_sorting_tasks.R
> +    file.copy(infile, file.path(cd, outfile), overwrite=TRUE)
I do not understand why, but this does seem to be necessary. I had to add it in to get the files to write to the correct location. I did a bunch more testing just now, and if I leave off the `cd` variable from the filepath either here _OR_ in the sorting step, then the files do not consistently write to the correct directory. No idea why. I am going to leave it for now, since we have other tasks and I can't determine why it doesn't work without that setting.

2021-02-26 20:12 UTC, hcorson-dosch commented on src/file_utils.R
> +        file.copy(these_files$source_filepath, file.path(cd,'tmp', these_files$out_file), overwrite=TRUE)
See above notes ^ . It does seem to be necessary here, and I do not know why, b/c I agree that it shouldn't be. I initially wrote it without this, but then had to add it in.

2021-02-26 20:22 UTC, hcorson-dosch commented on src/file_utils.R
> +        file.copy(these_files$source_filepath, file.path(cd,'tmp', these_files$out_file), overwrite=TRUE)
I'll test it again now, though, in case the behavior is different than the other case

2021-02-26 20:26 UTC, hcorson-dosch commented on src/file_utils.R
> +        file.copy(these_files$source_filepath, file.path(cd,'tmp', these_files$out_file), overwrite=TRUE)
Ok I think this one is fine actually, so I will edit this. I think the fact that it didn't work before is due to another piece of the function that I have since removed.

2021-02-26 20:27 UTC, lindsayplatt commented on src/do_sorting_tasks.R
> +    file.copy(infile, file.path(cd, outfile), overwrite=TRUE)
Huh, that seems so strange and contrary to how I would expect R to behave. Leaving for later is fine since we do have other tasks to do!

2021-02-26 20:27 UTC, lindsayplatt approved these changes

2021-02-26 21:05 UTC, hcorson-dosch commented on src/do_sorting_tasks.R
> +    file.copy(infile, file.path(cd, outfile), overwrite=TRUE)
So this was bugging me, so I tried some more. Once I deleted ALL of the existing prediction files (instead of only a few, to test on a subset of the sites), the code you suggested works 🤷‍♀️. So I made those changes and just pushed them.

2021-02-26 21:25 UTC, lindsayplatt commented on src/do_sorting_tasks.R
> +    file.copy(infile, file.path(cd, outfile), overwrite=TRUE)
Huh so bizarre. There probably is some explanation that we could dig into but I am good with just accepting that it is working now :)

2021-02-26 21:25 UTC, merged